---
- hosts: jekyll-hosts
  vars:
  remote_user: root

  tasks:

  - name: Unzip Github ~/bbs-jekyll-blog archive
    unarchive:  copy=no  src=https://github.com/keithrbennett/bbs-jekyll-blog/archive/master.zip  dest=/root

  - name: Add Brightbox Ubuntu repository
    apt_repository: repo=ppa:brightbox/ruby-ng

  - name: Install Ruby
    apt: update_cache=yes  name=ruby2.3,ruby2.3-dev  state=latest

  - name: Install gem build prerequisites
    apt:  name=build-essential,make  state=latest

  - name: Get Gem List
    shell: gem list | awk '{print $1}'
    register: gem_list

  - name: Install jekyll
    shell: gem install jekyll
    when: "'jekyll' not in gem_list.stdout_lines"

#  - name: Install Jekyll only if not yet installed
#    shell: gem install jekyll
#    args:
#      creates: /usr/local/bin/jekyll

#  - name: Install Jekyll only if not yet installed
#    shell: gem list | grep \"jekyll \" > /dev/null || gem install jekyll
#    shell: bash -lc "(gem list | grep \"jekyll \" > /dev/null || gem install jekyll)"

#    gem: name=jekyll  state=latest
